### ISSUE TITLE
hygieia_jenkins-build-collector docker container exits after couple of seconds

### ISSUE THREAD

**Issue by sbabutk** [Hygieia/Hygieia#2489]
I added required environment properties for Jenkins collector to docker-compose.override.yml file but docker container dies after couple of seconds. 

I believe the issue is "--spring.config.location" in Dockerfile is pointing to a non existing file called  "application.properties"

I modified the "collectors/build/jenkins/docker/Dockerfile" to point the spring config to "hygieia-jenkins-build-collector.properties" and now container starts up without any issues. 

`"ENV PROP_FILE /hygieia/config/hygieia-jenkins-build-collector.properties"`
 
https://github.com/Hygieia/Hygieia/blob/6ea1b067ffd1c59d4b280e2e455730c14dcb8f38/collectors/build/jenkins/docker/Dockerfile#L15

**Comment by matthewbeasley** [comment]
@sbabutk - if you'll notice the referenced line in the dockerfile is a `ENV` line. This means that if you add `-e PROP_FILE /path/to/expected/properties` it will override that variable without need for modifying the dockerfile. Ideally though you should be using the jenkins plugin we provide as there are some performance issues for the jenkins build collectors on jenkins instances with a large number of jobs.

**Comment by sbabutk** [comment]
Thank you, Jenkins plugin is working fine.

I was following the "https://hygieia.github.io/Hygieia/builddocker.html" to build and run docker image using maven and it failed so I still think it is a defect. (default config location is pointing to a test properties file instead of hygieia-jenkins-build-collector.properties)

**Comment by daniel-ng** [comment]
Agree with @sbabutk. Following the instructions on this site regarding creating and running the Docker Containers using docker-compose doesn't actually work and won't work for ANY of the collectors as they ALL have the same pattern of using application.properties rather than the name of what the actual properties files should be. I think it's worth correcting. Should just be a matter of changing the shall script use application.properties or modifying the Dockerfile to suit the collector.

**Comment by Sbrenthughes** [comment]
Can you make a PR?

**Comment by JFDonaghy** [comment]
Hello, everyone!

I've been trying to follow the Hygieia documentation @ https://hygieia.github.io/Hygieia/setup.html for about a week before stumbling onto this page. I second that alternative of modifying the instructions. At the very least, a fix like the one here should be more visible to newcomers learning this on their own (as I am) so that they don't get discouraged.

Thank you all for offering solutions to this problem!
