### ISSUE TITLE
Jira collector and gitlab collector not working completely

### ISSUE THREAD

**Issue by hvvit** [Hygieia/Hygieia#2827]
Not able to gitlab scm collector collect pulls and issues..
not able to make jira feature collect open,wip,issues detail, I am only able to fetch project teams and boards
**JIRA application.properties**
# Database Name
dbname=dashboarddb

# Database HostName - default is localhost
dbhost=localhost

# Database Port - default is 27017
dbport=27017

# MongoDB replicaset
dbreplicaset=[false if you are not using MongoDB replicaset]
dbhostport=[host1:port1,host2:port2,host3:port3]

# Database Username - default is blank
dbusername=dashboarduser

# Database Password - default is blank
dbpassword=dbpassword

# Logging File location
logging.file=./logs/jira.log

# PageSize - Expand contract this value depending on Jira implementation's
# default server timeout setting (You will likely receive a SocketTimeoutException)
feature.pageSize=100

# Delta change date that modulates the collector item task
# Occasionally, these values should be modified if database size is a concern
feature.deltaStartDate=2018-05-01T00:00:00.000000
feature.masterStartDate=2018-05-01T00:00:00.000000
feature.deltaCollectorItemStartDate=2018-05-01T00:00:00.000000

# Chron schedule: S M D M Y [Day of the Week]
feature.cron=0 * * * * *

# ST Query File Details - Required, but DO NOT MODIFY
feature.queryFolder=jiraapi-queries
feature.storyQuery=story
feature.epicQuery=epic

# JIRA CONNECTION DETAILS:
# Enterprise Proxy - ONLY INCLUDE IF YOU HAVE A PROXY
#feature.jiraProxyUrl=http://proxy.com
#feature.jiraProxyPort=9000
feature.jiraBaseUrl=https://xxxxxxxxxxxxxxxxxxx/
feature.jiraQueryEndpoint=rest/api/2/
# For basic authentication, requires username:password as string in base64
# This command will make this for you:  echo -n username:password | base64

feature.jiraCredentials=xxxxxxxxxxxxxxxx

# OAuth is not fully implemented; please blank-out the OAuth values:

feature.jiraOauthAuthtoken=
feature.jiraOauthRefreshtoken=
		feature.jiraOauthRedirecturi=
		feature.jiraOauthExpiretime=

#############################################################################
# In Jira, general IssueType IDs are associated to various 'issue'
# attributes. However, there is one attribute which this collector's
# queries rely on that change between different instantiations of Jira.
# Please provide a string name reference to your instance's IssueType for
# the lowest level of Issues (for example, 'user story') specific to your Jira
# instance.  Note:  You can retrieve your instance's IssueType Name
# listings via the following URI:  https://[your-jira-domain-name]/rest/api/2/issuetype/
# Multiple comma-separated values can be specified.
#############################################################################
feature.jiraIssueTypeNames=Story

#############################################################################
# In Jira, your instance will have its own custom field created for 'sprint' or 'timebox' details,
# which includes a list of information.  This field allows you to specify that data field for your
# instance of Jira. Note: You can retrieve your instance's sprint data field name
# via the following URI, and look for a package name com.atlassian.greenhopper.service.sprint.Sprint;
# your custom field name describes the values in this field:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
#############################################################################
feature.jiraSprintDataFieldName=customfield_10007

#############################################################################
# In Jira, your instance will have its own custom field created for 'super story' or 'epic' back-end ID,
# which includes a list of information.  This field allows you to specify that data field for your instance
# of Jira.  Note:  You can retrieve your instance's epic ID field name via the following URI where your
# queried user story issue has a super issue (for example, epic) tied to it; your custom field name describes the
# epic value you expect to see, and is the only field that does this for a given issue:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
#############################################################################
feature.jiraEpicIdFieldName=customfield_10008

#############################################################################
# In Jira, your instance will have its own custom field created for 'story points'
# This field allows you to specify that data field for your instance
# of Jira.  Note:  You can retrieve your instance's storypoints ID field name via the following URI where your
# queried user story issue has story points set on it; your custom field name describes the
# story points value you expect to see:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
#############################################################################
feature.jiraStoryPointsFieldName=customfield_10005

#############################################################################
# In Jira, your instance will have its own custom field created for 'team'
# This field allows you to specify that data field for your instance
# of Jira.  Note:  You can retrieve your instance's team ID field name via the following URI where your
# queried user story issue has team set on it; your custom field name describes the
# team value you expect to see:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
#############################################################################
feature.jiraTeamFieldName=

# Set this to true if you use boards as team
feature.jiraBoardAsTeam=true
**GITLAB application.properties**
# Database Name
dbname=dashboarddb

# Database HostName - default is localhost
dbhost=localhost

# Database Port - default is 27017
dbport=27017

# MongoDB replicaset
#dbreplicaset=[false if you are not using MongoDB replicaset]
#dbhostport=[host1:port1,host2:port2,host3:port3]
# Database Username - default is blank
dbusername=dashboarduser
# Database Password - default is blank
dbpassword=dbpassword

# Logging File location
logging.file=./logs/gitlabFeature.log

#Collector schedule (required)
gitlab.cron=0 0/1 * * * *

#Gitlab host (optional, defaults to 'gitlab.com')
gitlab.host=xxxxxxxxxxxxxxx

#Gitlab protocol (optional, defaults to 'http')
gitlab.protocol=https

#Gitlab port (optional, defaults to protocol default port)
gitlab.port=443

		#Gitlab path (optional, if your instance of Gitlab requires a path)
#gitlab.path=/gitlab/resides/here
		  
		#Gitlab API Token (required, collector will have permission of user associated to the token)
		#If token is from admin account, will be able to view all teams, and can collect all issues
		#If token is from standard user, will show only teams that user is a part of, and can only collect issues that user could view
		#It is recommended to create a Gitlab account for the collector, using its Access Token, and adding that user to the teams you want to see issues for
gitlab.apiToken=xxxxxxxxxxxx

#Gitlab selfSignedCertificate (optional, defaults to false, set to true if your instance of gitlab is running on https without a trusted certificate
		gitlab.selfSignedCertificate=true

		#Gitlab API Version (optional, defaults to current version of 4)
		gitlab.apiVersion=4
                gitlab.commitThresholdDays=20
                           #gitlab.key=xxxxxxxxx

**Comment by hvvit** [comment]
Here in jira feature i am to get project name and board names and no details are there present in the mongo db
![2](https://user-images.githubusercontent.com/49516671/55947198-a8842780-5c6b-11e9-9a5e-9a035c780ccd.PNG)
![1](https://user-images.githubusercontent.com/49516671/55947200-a8842780-5c6b-11e9-8994-b88e9df21742.PNG)
in gitlab scm widget i am not able to get pulls or issues

**Comment by Sbrenthughes** [comment]
For Jira, you are missing several required properties. Reread https://github.com/Hygieia/Hygieia/blob/gh-pages/pages/hygieia/collectors/feature/jira.md. For Gitlab, we have an open PR to add issues and PRs, see https://github.com/Hygieia/Hygieia/pull/2755

**Comment by hvvit** [comment]
> For Jira, you are missing several required properties. Reread https://github.com/Hygieia/Hygieia/blob/gh-pages/pages/hygieia/collectors/feature/jira.md. For Gitlab, we have an open PR to add issues and PRs, see #2755
I took the sample application.properties file from the hygieia documentation itself...
dbname=dashboarddb
dbhost=localhost
dbport=27017
dbreplicaset=[false if you are not using MongoDB replicaset]###using mongodb
dbhostport=[host1:port1,host2:port2,host3:port3]###dbport i have mentioned earlier
dbusername=dashboarduser
dbpassword=dbpassword
logging.file=./logs/jira.log
feature.pageSize=100
feature.deltaStartDate=2018-05-01T00:00:00.000000
feature.masterStartDate=2018-05-01T00:00:00.000000
feature.deltaCollectorItemStartDate=2018-05-01T00:00:00.000000
feature.cron=0 * * * * *
feature.queryFolder=jiraapi-queries
feature.storyQuery=story
feature.epicQuery=epic
feature.jiraBaseUrl=https://xxxxxxxxxxxxxxxxxxxxxxx.com/
feature.jiraQueryEndpoint=rest/api/2/
feature.jiraCredentials=xxxxxxxxxxxxxxxxxxxxxxxx
######I have not implemented Outh that's y these values are empty
feature.jiraOauthAuthtoken=
feature.jiraOauthRefreshtoken=
		feature.jiraOauthRedirecturi=
		feature.jiraOauthExpiretime=
feature.jiraIssueTypeNames=Story
feature.jiraSprintDataFieldName=customfield_10007
feature.jiraEpicIdFieldName=customfield_10008
feature.jiraStoryPointsFieldName=customfield_10005
#####we dont have team thats y left blank we have boards
feature.jiraTeamFieldName=
feature.jiraBoardAsTeam=true
I have filled these details previously , if i am still missing something please help me...

**Comment by Sbrenthughes** [comment]
Please see my link to the documentation for Jira.

**Comment by Sbrenthughes** [comment]
@hvvit any update here?

**Comment by hvvit** [comment]
[{"self":"https:/xxxxxxxxxxxxxxxx/rest/api/2/issuetype/3","id":"3","description":"A task that needs to be done.","iconUrl":"https://xxxxxxxxxxxxxxxxxxxxxxxx/secure/viewavatar?size=xsmall&avatarId=10318&avatarType=issuetype","name":"Task","subtask":false,"avatarId":10318},{"self":"https:/xxxxxxxxxxxxxxxx/rest/api/2/issuetype/5","id":"5","description":"The sub-task of the issue","iconUrl":"https://xxxxxxxxxxxxxxxxxxxx?size=xsmall&avatarId=10316&avatarType=issuetype","name":"Sub-task","subtask":true,"avatarId":10316},{"self":"https://xxxxxxxxxxxm.com/rest/api/2/issuetype/10001","id":"10001","description":"Created by Jira Software - do not edit or delete. Issue type for a user story.","iconUrl":"https://xxxxxxxxxxx/secure/viewavatar?size=xsmall&avatarId=10315&avatarType=issuetype","name":"Story","subtask":false,"avatarId":10315},{"self":"https:/xxxxxxxxx/rest/api/2/issuetype/1","id":"1","description":"A problem which impairs or prevents the functions of the product.","iconUrl":"https://xxxxxxxxxxxxx/secure/viewavatar?size=xsmall&avatarId=10303&avatarType=issuetype","name":"Bug","subtask":false,"avatarId":10303},{"self":"https://xxxxxxxxxx/rest/api/2/issuetype/10000","id":"10000","description":"Created by Jira Software - do not edit or delete. Issue type for a big user story that needs to be broken down.","iconUrl":"https://xxxxxxxxxxxx/secure/viewavatar?size=xsmall&avatarId=10307&avatarType=issuetype","name":"Epic","subtask":false,"avatarId":10307},{"self":"https://xxxxxxxxxxxxxx/rest/api/2/issuetype/4","id":"4","description":"An improvement or enhancement to an existing feature or task.","iconUrl":"https://xxxxxxxxxxxxxxxx/secure/viewavatar?size=xsmall&avatarId=10310&avatarType=issuetype","name":"Improvement","subtask":false,"avatarId":10310},{"self":"https://xxxxxxxxxxxxx/rest/api/2/issuetype/10300","id":"10300","description":"","iconUrl":"https://xxxxxxxxxxxxxxxxxx/secure/viewavatar?size=xsmall&avatarId=10304&avatarType=issuetype","name":"Project Status","subtask":false,"avatarId":10304}




This is a sample output for xxxxxxxxx/rest/api/2/issueType
so how does one decide the story ids and epic ids just by searching name....
for now if i set feature.jiraStoryIds[0]=10001 & feature.jiraEpicId=10000 it doesnt work.....
or do i have to specific about the story IDs like TAR-1212 or CHK-1210

**Comment by Sbrenthughes** [comment]
When you make the changes `feature.jiraStoryIds[0]=10001 & feature.jiraEpicId=10000` what do you see in the logs?

**Comment by Sbrenthughes** [comment]
Can you paste this url in the browser `https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]` for an issue, scrub the data clean of any company specific information and then paste the response here

**Comment by Sbrenthughes** [comment]
@hvvit any update here?

**Comment by mitunmbj** [comment]
brother you are the right one providing solutions can u please provide ur property file
and say me the step by step ways to get right customfield ids

**Comment by mitunmbj** [comment]
@Sbrenthughes please read above

**Comment by mitunmbj** [comment]
@i configured rest collectors and it works fine except jira

**Comment by mitunmbj** [comment]
dbname=admin
dbhost=localhost
dbport=27017
dbreplicaset=false
dbhostport=[host1:port1]
dbusername=admin123
dbpassword=password
logging.file=./logs/jira.log
feature.pageSize=50
feature.deltaStartDate=2016-03-01T00:00:00.000000
feature.masterStartDate=2016-03-01T00:00:00.000000
feature.deltaCollectorItemStartDate=2016-03-01T00:00:00.000000
feature.cron=0 * * * * *
feature.queryFolder=jiraapi-queries
feature.storyQuery=story
feature.epicQuery=epic
feature.jiraBaseUrl=https://mitunmbj.atlassian.net/
#feature.jiraQueryEndpoint=rest/api/2/
feature.jiraCredentials=mitunmbj@gmail.com:zippyops
feature.jiraIssueTypeNames=Story,Bug,Task,Sub-Task

feature.jiraSprintDataFieldName=customfield_10021
feature.jiraEpicIdFieldName=customfield_10000
feature.jiraStoryPointsFieldName=customfield_10016
feature.jiraStoryIds[0]=customfield_10001
feature.jiraEpicId=customfield_10000

feature.jiraBoardAsTeam=true

**Comment by mitunmbj** [comment]
2019-04-23 11:48:00,001 INFO  c.c.d.collector.CollectorTask - Running Collector: Jira
2019-04-23 11:48:00,124 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-04-23 11:48:00,125 INFO  c.c.d.collector.CollectorTask - https://mitunmbj.atlassian.net/
2019-04-23 11:48:00,132 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-04-23 11:48:00,133 INFO  c.c.d.collector.FeatureCollectorTask - JIRA Collector is set to work in Board mode
2019-04-23 11:48:00,133 INFO  c.c.d.collector.FeatureCollectorTask - Hours since last run = 0. Collector is only collecting updated/new issues.
2019-04-23 11:48:00,148 INFO  c.c.d.collector.CollectorTask - Finished                         0s

**Comment by Sbrenthughes** [comment]
For each of these `feature.jiraIssueTypeNames=Story,Bug,Task,Sub-Task,Epic` you need to go to `https://[your-jira-domain-name]/rest/api/2/issuetype` in your browser and get each of their ids. Next you need to add them to the properties file:
```
feature.jiraStoryIds[0]=[Story-id]
feature.jiraStoryIds[1]=[Bug-id]
feature.jiraStoryIds[2]=[Task-id]
feature.jiraStoryIds[3]=[Sub-Task-id]

feature.jiraEpicId=[Epic-id]
```
I am not sure where you found to do `feature.jiraStoryIds[0]=customfield_10001`
`feature.jiraEpicId=customfield_10000`.  Can you show me where you found this so that I can correct it?

**Comment by mitunmbj** [comment]
thanks for quick reply brother
2019-04-23 23:13:00,273 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-04-23 23:13:00,274 INFO  c.c.d.collector.CollectorTask - https://mitunmbj.atlassian.net/
2019-04-23 23:13:00,274 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-04-23 23:13:00,418 INFO  c.c.d.collector.FeatureCollectorTask - JIRA Collector is set to work in Board mode
2019-04-23 23:13:00,422 INFO  c.c.d.collector.FeatureCollectorTask - Hours since last run = 432233. Collector is about to refresh Team/Board information
**2019-04-23 23:13:03,212 ERROR c.c.d.collector.DefaultJiraClient - Error in calling JIRA API: https://mitunmbj.atlassian.net/rest/agile/1.0/board?startAt=0**
2019-04-23 23:13:03,216 INFO  c.c.d.collector.CollectorTask - Board Data Collected. Added  0        2s
2019-04-23 23:13:03,654 INFO  c.c.d.collector.CollectorTask - Project Data Collected  0        0s
2019-04-23 23:13:03,819 INFO  c.c.d.collector.CollectorTask - Board Issues Refreshed           0s
2019-04-23 23:13:03,838 INFO  c.c.d.collector.FeatureCollectorTask - Collected 0 teams and 0 projects
2019-04-23 23:13:03,867 INFO  c.c.d.collector.CollectorTask - Finished                         3s
2019-04-23 23:14:00,002 INFO  c.c.d.collector.CollectorTask - Running Collector: Jira
2019-04-23 23:14:00,103 INFO  c.c.d.collector.CollectorTask - -----------------------------------

**Comment by mitunmbj** [comment]
brother do you need my property file

**Comment by mitunmbj** [comment]
i provided the ids now its showing
2019-04-23 23:45:00,005 INFO  c.c.d.collector.CollectorTask - Running Collector: Jira
2019-04-23 23:45:00,220 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-04-23 23:45:00,220 INFO  c.c.d.collector.CollectorTask - https://mitunmbj.atlassian.net/
2019-04-23 23:45:00,220 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-04-23 23:45:00,372 INFO  c.c.d.collector.FeatureCollectorTask - JIRA Collector is set to work in Board mode
2019-04-23 23:45:00,401 INFO  c.c.d.collector.FeatureCollectorTask - Hours since last run = 0. Collector is only collecting updated/new issues.
2019-04-23 23:45:00,725 INFO  c.c.d.collector.CollectorTask - Finished                         0s
2019-04-23 23:46:00,000 INFO  c.c.d.collector.CollectorTask - Running Collector: Jira
2019-04-23 23:46:00,146 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-04-23 23:46:00,147 INFO  c.c.d.collector.CollectorTask - https://mitunmbj.atlassian.net/
2019-04-23 23:46:00,147 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-04-23 23:46:00,148 INFO  c.c.d.collector.FeatureCollectorTask - JIRA Collector is set to work in Board mode
2019-04-23 23:46:00,148 INFO  c.c.d.collector.FeatureCollectorTask - Hours since last run = 0. Collector is only collecting updated/new issues.
2019-04-23 23:46:00,171 INFO  c.c.d.collector.CollectorTask - Finished                         0s
2019-04-23 23:47:00,007 INFO  c.c.d.collector.CollectorTask - Running Collector: Jira
2019-04-23 23:47:00,078 INFO  c.c.d.collector.CollectorTask - -----------------------------------

**Comment by mitunmbj** [comment]
dbname=admin

# Database HostName - default is localhost
dbhost=localhost

# Database Port - default is 27017
dbport=27017

# MongoDB replicaset
dbreplicaset=false
dbhostport=[host1:port1,host2:port2,host3:port3]

# Database Username - default is blank
dbusername=admin123

# Database Password - default is blank
dbpassword=password

# Logging File location
logging.file=./logs/jira.log

# PageSize - Expand contract this value depending on Jira implementation's
# default server timeout setting (You will likely receive a SocketTimeoutException)
feature.pageSize=50

# Delta change date that modulates the collector item task
# Occasionally, these values should be modified if database size is a concern
feature.deltaStartDate=2016-03-01T00:00:00.000000
feature.masterStartDate=2016-03-01T00:00:00.000000
feature.deltaCollectorItemStartDate=2016-03-01T00:00:00.000000

# Chron schedule: S M D M Y [Day of the Week]
feature.cron=0 * * * * *

# ST Query File Details - Required, but DO NOT MODIFY
feature.queryFolder=jiraapi-queries
feature.storyQuery=story
feature.epicQuery=epic
feature.projectQuery=projectinfo
feature.memberQuery=memberinfo
feature.sprintQuery=sprintinfo
feature.teamQuery=teaminfo
feature.trendingQuery=trendinginfo



# JIRA CONNECTION DETAILS:
# Enterprise Proxy - ONLY INCLUDE IF YOU HAVE A PROXY
#feature.jiraProxyUrl=http://proxy.com
#feature.jiraProxyPort=9000
feature.jiraBaseUrl=https://mitunmbj.atlassian.net/
feature.jiraQueryEndpoint=rest/api/2/
feature.jiraCredentials=********************
feature.jiraIssueTypeNames=Story
feature.jiraSprintDataFieldName=customfield_10021
feature.jiraEpicIdFieldName=customfield_10011
feature.jiraStoryPointsFieldName=customfield_10016
#feature.jiraTeamFieldName=

feature.jiraStoryIds[0]=10001
feature.jiraStoryIds[1]=10004
feature.jiraStoryIds[2]=10002
feature.jiraStoryIds[3]=10003
feature.jiraEpicId=10000
#feature.collectorItemOnlyUpdate=


#feature.maxNumberOfFeaturesPerBoard=
feature.todoStatuses[0]=To Do
feature.doingStatuses[0]=In Progress
feature.doneStatuses[0]=Done
feature.jiraBoardAsTeam=true

**Comment by mitunmbj** [comment]
expecting your fast reply

**Comment by mitunmbj** [comment]
brother i just removed credentials and ran it as per norms the error should have came unauthorized but the collocter not showing such errors and running like this every time
2019-04-24 00:10:00,287 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-04-24 00:10:00,287 INFO  c.c.d.collector.CollectorTask - https://mitunmbj.atlassian.net/
2019-04-24 00:10:00,287 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-04-24 00:10:00,391 INFO  c.c.d.collector.FeatureCollectorTask - JIRA Collector is set to work in Board mode
2019-04-24 00:10:00,392 INFO  c.c.d.collector.FeatureCollectorTask - Hours since last run = 0. Collector is only collecting updated/new issues.
2019-04-24 00:10:00,559 INFO  c.c.d.collector.CollectorTask - Finished                         0s
2019-04-24 00:11:00,007 INFO  c.c.d.collector.CollectorTask - Running Collector: Jira
2019-04-24 00:11:00,084 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-04-24 00:11:00,085 INFO  c.c.d.collector.CollectorTask - https://mitunmbj.atlassian.net/
2019-04-24 00:11:00,085 INFO  c.c.d.collector.CollectorTask - -----------------------------------

**Comment by Sbrenthughes** [comment]
`eature.jiraIssueTypeNames=Story,Bug,Task,Sub-Task,Epic` needs to be added back

**Comment by mitunmbj** [comment]
brother still the same type of output

**Comment by mitunmbj** [comment]
It is not hitting the url even if i given password wron it should have shown unauthorized but it is comming as it as same error

**Comment by mitunmbj** [comment]
@Sbrenthughes plz do reply bro......
2019-04-24 16:37:00,469 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-04-24 16:37:00,470 INFO  c.c.d.collector.CollectorTask - https://mitunmbj.atlassian.net/
2019-04-24 16:37:00,470 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-04-24 16:37:00,557 INFO  c.c.d.collector.FeatureCollectorTask - JIRA Collector is set to work in Board mode
2019-04-24 16:37:00,559 INFO  c.c.d.collector.FeatureCollectorTask - Hours since last run = 432251. Collector is about to refresh Team/Board information
2019-04-24 16:37:02,245 ERROR c.c.d.collector.DefaultJiraClient - Error in calling JIRA API: https://mitunmbj.atlassian.net/rest/agile/1.0/board?startAt=0
2019-04-24 16:37:02,249 INFO  c.c.d.collector.CollectorTask - Board Data Collected. Added  0        1s
2019-04-24 16:37:02,960 ERROR c.c.d.collector.FeatureCollectorTask - Failed to collect jira information
org.springframework.web.client.HttpClientErrorException: 401 null

**Comment by mitunmbj** [comment]
if is pasted the url it shows the data but jira collector not fetching it bro

**Comment by hvvit** [comment]
tried all the permutations and combinations...still ...changed customfields..,storyids...its able to pick board names and project names but it is not able to pick data

**Comment by Sbrenthughes** [comment]
@hvvit Please reach out to me directly on Gitter.

**Comment by Sbrenthughes** [comment]
https://gitter.im/capitalone/Hygieia @hvvit

**Comment by GuptaHimanshu** [comment]
I am facing similar issue.
If you guys were able to fix it, then can you please share it with me.
