### ISSUE TITLE
Hygieia Product View Build stage not showing metrics.

### ISSUE THREAD

**Issue by gopiprasanthpotipireddy** [Hygieia/Hygieia#2893]
I configured product view and repos and build are having commits. but build stage is not showing any metrics like average time and standard deviation

**Comment by gopiprasanthpotipireddy** [comment]
@nireeshT @tabladrum commits are not moving from commit stage to build also.

**Comment by Sbrenthughes** [comment]
What tool are you using for you builds?

**Comment by IATVirtusa** [comment]
I am using Jenkins Hygieia Plug in to publish Build and Deploy Jobs.
I am able to get metrics like avg time and sd in Build and Commit stage. but, Deploy Stage is not getting any metrics. i think the issue is similar to  [https://github.com/Hygieia/Hygieia/issues/2832] .

![Screenshot (28)](https://user-images.githubusercontent.com/48546034/58151524-87115500-7c87-11e9-9118-4206b1df39ba.png)

i am pasting my artifact and deploy information here .
![Screenshot (29)](https://user-images.githubusercontent.com/48546034/58151568-a9a36e00-7c87-11e9-931f-0a97e406060f.png)

**Comment by gopiprasanthpotipireddy** [comment]
@rvema can you look in to this ? i am not getting any commit info in environments other than commit and build. i am using jenkins-hygieia plugin for deploy widget.

**Comment by jjoyneriv** [comment]
@gopiprasanthpotipireddy , I’m having the same problem. What was your fix?

**Comment by gopiprasanthpotipireddy** [comment]
No fix @jjoyneriv the jenkins plugin is not having any commit data with it. that is plugin coding issue.
