### ISSUE TITLE
Unable to get deploy collector data on the Product Dashboard

### ISSUE THREAD

**Issue by GuptaHimanshu** [Hygieia/Hygieia#3299]
Currently i've seen that there is a plugin for jenkins which shows the status of build in different environment stages. One member of our team made changes to the deploy collector to fetch data from PCF. But that status is not visible on the product dashboard. For the build widget data, i've made changes to the jenkins collector to fetch data from TeamCity.

Can someone help me in figuring out what and where the changes are required for this to make it work ?

**Comment by rvema** [comment]
try disabling `auto publish build data` option in the plugin

**Comment by GuptaHimanshu** [comment]
im not using Jenkins plugin.
Im using the TeamCity collector to fetch data on the team dashboard.

**Comment by GuptaHimanshu** [comment]
Basically i want to show the status of application which i am fetching from PCF on the Product Dashboard. I dont have much knowledge of front end and therefore requesting help for making changes if required to the UI or the PCF deploy collector to show its status on the Product dashboard.

**Comment by chintalaabhi** [comment]
This worked for me https://github.com/Hygieia/Hygieia/issues/3291#issuecomment-689284105

**Comment by chintalaabhi** [comment]
The problem was a code error. PipelineController.java line 33 is incorrect.
package com.capitalone.dashboard.rest;

import com.capitalone.dashboard.misc.HygieiaException;
import com.capitalone.dashboard.model.PipelineResponse;
import com.capitalone.dashboard.request.PipelineSearchRequest;
import com.capitalone.dashboard.service.PipelineService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import javax.validation.Valid;

import org.springframework.web.bind.annotation.RequestParam;
import java.util.ArrayList;
import java.util.List;
import org.bson.types.ObjectId;

import static org.springframework.http.MediaType.APPLICATION_JSON_VALUE;
import static org.springframework.web.bind.annotation.RequestMethod.GET;

@RestController
public class PipelineController {
    private final PipelineService pipelineService;

    @Autowired
    public PipelineController(PipelineService pipelineService) {
        this.pipelineService = pipelineService;
    }

    @RequestMapping(value = "/pipeline", method = GET, produces = APPLICATION_JSON_VALUE)

    public Iterable searchPipelines(@RequestParam String collectorItemId, @RequestParam String beginDate, @RequestParam String endDate) throws HygieiaException {
        PipelineSearchRequest pipelineSearchRequest = new PipelineSearchRequest();
        pipelineSearchRequest.setBeginDate(Long.valueOf(beginDate));
        pipelineSearchRequest.setEndDate(Long.valueOf(endDate));
        List collectorItemIdList = new ArrayList<>();
        collectorItemIdList.add(new ObjectId(collectorItemId));
        pipelineSearchRequest.setCollectorItemId(collectorItemIdList);
        return pipelineService.search(pipelineSearchRequest);
    } 
}

**Comment by chintalaabhi** [comment]
The problem was a code error. PipelineController.java line 33 is incorrect.
`package com.capitalone.dashboard.rest;

import com.capitalone.dashboard.misc.HygieiaException;
import com.capitalone.dashboard.model.PipelineResponse;
import com.capitalone.dashboard.request.PipelineSearchRequest;
import com.capitalone.dashboard.service.PipelineService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import javax.validation.Valid;

import org.springframework.web.bind.annotation.RequestParam;
import java.util.ArrayList;
import java.util.List;
import org.bson.types.ObjectId;

import static org.springframework.http.MediaType.APPLICATION_JSON_VALUE;
import static org.springframework.web.bind.annotation.RequestMethod.GET;

@RestController
public class PipelineController {
private final PipelineService pipelineService;

@Autowired
public PipelineController(PipelineService pipelineService) {
    this.pipelineService = pipelineService;
}

@RequestMapping(value = "/pipeline", method = GET, produces = APPLICATION_JSON_VALUE)

public Iterable searchPipelines(@RequestParam String collectorItemId, @RequestParam String beginDate, @RequestParam String endDate) throws HygieiaException {
    PipelineSearchRequest pipelineSearchRequest = new PipelineSearchRequest();
    pipelineSearchRequest.setBeginDate(Long.valueOf(beginDate));
    pipelineSearchRequest.setEndDate(Long.valueOf(endDate));
    List collectorItemIdList = new ArrayList<>();
    collectorItemIdList.add(new ObjectId(collectorItemId));
    pipelineSearchRequest.setCollectorItemId(collectorItemIdList);
    return pipelineService.search(pipelineSearchRequest);
} 
}`

**Comment by chintalaabhi** [comment]
Check this out https://github.com/Hygieia/Hygieia/issues/3291#issue-672508409

**Comment by chintalaabhi** [comment]
#3291 has a fix
