### ISSUE TITLE
Fix instructions readme for collectors - Phase 1

### ISSUE THREAD

**Issue by rvema** [Hygieia/Hygieia#3320]

**Comment by rvema** [comment]
@Courtneyp123 please populate this issue with details of the collectors where you fixed the documentation

**Comment by Courtneyp123** [comment]
**Documentation fixed in README:** 

https://github.com/Hygieia/api-audit/pull/63
https://github.com/Hygieia/api/pull/167
https://github.com/Hygieia/hygieia-whitesource-collector/pull/24
https://github.com/Hygieia/hygieia-codequality-sonar-collector/pull/67
https://github.com/Hygieia/hygieia-scm-subversion-collector/pull/25
https://github.com/Hygieia/hygieia-scm-github-collector/pull/28
https://github.com/Hygieia/hygieia-build-jenkins-collector/pull/40
https://github.com/Hygieia/hygieia-feature-jira-collector/pull/53
https://github.com/Hygieia/hygieia-misc-score-collector/pull/21
https://github.com/Hygieia/hygieia-scm-github-graphql-collector/pull/54

**Comment by Courtneyp123** [comment]
Fixed README documentation per requests: https://github.com/Hygieia/UI/blob/master/README.md

**Comment by VivekBuzruk** [comment]
I am trying Jenkins codequality collector but facing certain challenges. Wish README documentation of [Jenkins codequality](https://github.com/Hygieia/hygieia-codequality-jenkins-collector) is also being updated.

**Comment by rvema** [comment]
> I am trying Jenkins codequality collector but facing certain challenges. Wish README documentation of [Jenkins codequality](https://github.com/Hygieia/hygieia-codequality-jenkins-collector) is also being updated.

please create an issue under the appropriate collector
